#!/usr/bin/env python3
"""
kb_index.py — regenerate index/index.json, index/index.jsonl, index/llms.txt,
and INDEX.md from every KB document's frontmatter in this repo.

Deterministic, no LLM calls: relations (related/supersedes/tags) come straight
from frontmatter that a human already declared. Filters out sensitivity levels
above what the caller requests (used by kb-home's cross-repo org-index build,
which must only ever see 'internal' and below).

Usage:
    python kb_index.py [--repo-root .] [--max-sensitivity restricted]
"""
from __future__ import annotations

import datetime
import json
import subprocess
import sys
from pathlib import Path

import frontmatter

REPO_ROOT = Path(sys.argv[sys.argv.index("--repo-root") + 1]) if "--repo-root" in sys.argv else Path(".")
MAX_SENSITIVITY = (
    sys.argv[sys.argv.index("--max-sensitivity") + 1]
    if "--max-sensitivity" in sys.argv else "restricted"
)
SENSITIVITY_RANK = {"public": 0, "internal": 1, "confidential": 2, "restricted": 3}


def commit_sha() -> str:
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO_ROOT,
            capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def collect_docs() -> list[dict]:
    docs = []
    for path in sorted(REPO_ROOT.rglob("*.md")):
        if ".git" in path.parts or path.name in ("README.md", "INDEX.md", "AGENTS.md"):
            continue
        try:
            post = frontmatter.load(path)
        except Exception:
            continue
        meta = post.metadata
        if "id" not in meta or "sensitivity" not in meta:
            continue  # not a KB doc (schema violation is kb_lint's job, not ours)
        if SENSITIVITY_RANK.get(meta["sensitivity"], 3) > SENSITIVITY_RANK[MAX_SENSITIVITY]:
            continue
        if meta.get("status") == "superseded" and "90-archive" not in str(path):
            continue
        docs.append({
            "id": meta["id"],
            "path": str(path.relative_to(REPO_ROOT)),
            "title_th": meta.get("title_th"),
            "title_en": meta.get("title_en"),
            "doc_type": meta.get("doc_type"),
            "project": meta.get("project"),
            "status": meta.get("status"),
            "sensitivity": meta.get("sensitivity"),
            "lang": meta.get("lang"),
            "last_updated": str(meta.get("last_updated")),
            "review_by": str(meta.get("review_by")),
            "owner": meta.get("owner"),
            "managers": meta.get("managers", []),
            "summary_en": meta.get("summary_en"),
            "summary_en_status": meta.get("summary_en_status"),
            "keywords_th": meta.get("keywords_th", []),
            "tags": meta.get("tags", []),
            "supersedes": meta.get("supersedes", []),
            "related": meta.get("related", []),
        })
    return docs


def write_index_json(docs: list[dict]) -> None:
    out = {
        "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
        "commit_sha": commit_sha(),
        "generator_version": "kb-index@v1",
        "doc_count": len(docs),
        "docs": docs,
    }
    idx_dir = REPO_ROOT / "index"
    idx_dir.mkdir(exist_ok=True)
    (idx_dir / "index.json").write_text(json.dumps(out, ensure_ascii=False, indent=2), encoding="utf-8")
    with open(idx_dir / "index.jsonl", "w", encoding="utf-8") as f:
        for d in docs:
            f.write(json.dumps(d, ensure_ascii=False) + "\n")


def write_llms_txt(docs: list[dict]) -> None:
    lines = ["# KB index (llms.txt style)", ""]
    by_type: dict[str, list[dict]] = {}
    for d in docs:
        by_type.setdefault(d["doc_type"] or "other", []).append(d)
    for doc_type, items in sorted(by_type.items()):
        lines.append(f"## {doc_type}")
        for d in sorted(items, key=lambda x: x["path"]):
            summary = (d.get("summary_en") or "").strip().replace("\n", " ")
            lines.append(f"- [{d['title_en'] or d['id']}]({d['path']}): {summary}")
        lines.append("")
    (REPO_ROOT / "index" / "llms.txt").write_text("\n".join(lines), encoding="utf-8")


def write_index_md(docs: list[dict]) -> None:
    lines = ["# INDEX", "", "> Auto-generated by `kb_index.py` — do not edit by hand.", ""]
    by_type: dict[str, list[dict]] = {}
    for d in docs:
        by_type.setdefault(d["doc_type"] or "other", []).append(d)
    for doc_type, items in sorted(by_type.items()):
        lines.append(f"## {doc_type}")
        lines.append("")
        lines.append("| title | status | sensitivity | last_updated | owner |")
        lines.append("|---|---|---|---|---|")
        for d in sorted(items, key=lambda x: x["path"]):
            lines.append(
                f"| [{d['title_th']}]({d['path']}) | {d['status']} | {d['sensitivity']} | "
                f"{d['last_updated']} | {d['owner']} |"
            )
        lines.append("")
    (REPO_ROOT / "INDEX.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    docs = collect_docs()
    write_index_json(docs)
    write_llms_txt(docs)
    write_index_md(docs)
    print(f"kb-index: wrote {len(docs)} doc(s) to index/index.json, index/llms.txt, INDEX.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
